-- MySQL Script generated by MySQL Workbench
-- Mon Sep 14 10:38:32 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ifsc60
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ifsc60` ;

-- -----------------------------------------------------
-- Schema ifsc60
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ifsc60` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `ifsc60` ;

-- -----------------------------------------------------
-- Table `ifsc60`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ifsc60`.`usuario` (
  `email` VARCHAR(100) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(15) NULL DEFAULT NULL,
  `CPF` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ifsc60`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ifsc60`.`administrador` (
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`email`),
  CONSTRAINT `administrador_ibfk_1`
    FOREIGN KEY (`email`)
    REFERENCES `ifsc60`.`usuario` (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ifsc60`.`bolsista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ifsc60`.`bolsista` (
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`email`),
  CONSTRAINT `bolsista_ibfk_1`
    FOREIGN KEY (`email`)
    REFERENCES `ifsc60`.`usuario` (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ifsc60`.`coordenador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ifsc60`.`coordenador` (
  `email` VARCHAR(100) NOT NULL,
  `SIAPE` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`email`),
  CONSTRAINT `coordenador_ibfk_1`
    FOREIGN KEY (`email`)
    REFERENCES `ifsc60`.`usuario` (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ifsc60`.`ministrante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ifsc60`.`ministrante` (
  `email` VARCHAR(100) NOT NULL,
  `nome` VARCHAR(200) NOT NULL,
  `telefone` VARCHAR(15) NULL DEFAULT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ifsc60`.`oficina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ifsc60`.`oficina` (
  `idOficina` INT NOT NULL AUTO_INCREMENT,
  `ministrante_email` VARCHAR(100) NOT NULL,
  `titulo` VARCHAR(50) NOT NULL,
  `descricao` VARCHAR(1200) NULL DEFAULT NULL,
  `local` VARCHAR(1200) NULL DEFAULT NULL,
  `dt_inicio` DATE NOT NULL,
  `dt_termino` DATE NOT NULL,
  `duracaoHr` INT NOT NULL,
  PRIMARY KEY (`idOficina`),
  INDEX `fk_oficina_ministrante1_idx` (`ministrante_email` ASC) VISIBLE,
  CONSTRAINT `fk_oficina_ministrante1`
    FOREIGN KEY (`ministrante_email`)
    REFERENCES `ifsc60`.`ministrante` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ifsc60`.`dia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ifsc60`.`dia` (
  `dtOficinaDia` DATE NOT NULL,
  PRIMARY KEY (`dtOficinaDia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ifsc60`.`participante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ifsc60`.`participante` (
  `idParticipante` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `CPF` VARCHAR(14) NULL DEFAULT NULL,
  `telefone` VARCHAR(15) NULL DEFAULT NULL,
  PRIMARY KEY (`idParticipante`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ifsc60`.`participa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ifsc60`.`participa` (
  `idParticipante` INT NOT NULL,
  `dia_dtOficinaDia` DATE NOT NULL,
  `oficina_idOficina` INT NOT NULL,
  `frequencia` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`idParticipante`, `dia_dtOficinaDia`),
  INDEX `fk_participa_dia1_idx` (`dia_dtOficinaDia` ASC) VISIBLE,
  INDEX `fk_participa_oficina1_idx` (`oficina_idOficina` ASC) VISIBLE,
  CONSTRAINT `participa_ibfk_1`
    FOREIGN KEY (`idParticipante`)
    REFERENCES `ifsc60`.`participante` (`idParticipante`),
  CONSTRAINT `fk_participa_dia1`
    FOREIGN KEY (`dia_dtOficinaDia`)
    REFERENCES `ifsc60`.`dia` (`dtOficinaDia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_participa_oficina1`
    FOREIGN KEY (`oficina_idOficina`)
    REFERENCES `ifsc60`.`oficina` (`idOficina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ifsc60`.`recuperacao_senha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ifsc60`.`recuperacao_senha` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `codigo` VARCHAR(6) NOT NULL,
  `expira_em` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `email` (`email` ASC) VISIBLE,
  CONSTRAINT `recuperacao_senha_ibfk_1`
    FOREIGN KEY (`email`)
    REFERENCES `ifsc60`.`usuario` (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ifsc60`.`usuario_monitora_oficina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ifsc60`.`usuario_monitora_oficina` (
  `usuario_email` VARCHAR(100) NOT NULL,
  `oficina_idOficina` INT NOT NULL,
  PRIMARY KEY (`usuario_email`, `oficina_idOficina`),
  INDEX `fk_usuario_has_oficina_oficina1_idx` (`oficina_idOficina` ASC) VISIBLE,
  INDEX `fk_usuario_has_oficina_usuario1_idx` (`usuario_email` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_has_oficina_usuario1`
    FOREIGN KEY (`usuario_email`)
    REFERENCES `ifsc60`.`usuario` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_oficina_oficina1`
    FOREIGN KEY (`oficina_idOficina`)
    REFERENCES `ifsc60`.`oficina` (`idOficina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ifsc60`.`oficina_acontece_dia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ifsc60`.`oficina_acontece_dia` (
  `oficina_idOficina` INT NOT NULL,
  `dia_dtOficinaDia` DATE NOT NULL,
  PRIMARY KEY (`oficina_idOficina`, `dia_dtOficinaDia`),
  INDEX `fk_oficina_has_dia_dia1_idx` (`dia_dtOficinaDia` ASC) VISIBLE,
  INDEX `fk_oficina_has_dia_oficina1_idx` (`oficina_idOficina` ASC) VISIBLE,
  CONSTRAINT `fk_oficina_has_dia_oficina1`
    FOREIGN KEY (`oficina_idOficina`)
    REFERENCES `ifsc60`.`oficina` (`idOficina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_oficina_has_dia_dia1`
    FOREIGN KEY (`dia_dtOficinaDia`)
    REFERENCES `ifsc60`.`dia` (`dtOficinaDia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `ifsc60`.`usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `ifsc60`;
INSERT INTO `ifsc60`.`usuario` (`email`, `nome`, `senha`, `telefone`, `CPF`) VALUES ('kiara.s18@ifsc.edu.br', 'Kiara Annelise da Silva Souza', '12345', '47999999999', '00000000001');
INSERT INTO `ifsc60`.`usuario` (`email`, `nome`, `senha`, `telefone`, `CPF`) VALUES ('heloisa.mr@aluno.ifsc.edu.br', 'Heloísa Mafra Reisch', '12345', '47999999999', '00000000002');
INSERT INTO `ifsc60`.`usuario` (`email`, `nome`, `senha`, `telefone`, `CPF`) VALUES ('oliver.cs11@aluno.ifsc.edu.br', 'Oliver Cristine da Silva dos Santo', '12345', '47999999999', '00000000003');
INSERT INTO `ifsc60`.`usuario` (`email`, `nome`, `senha`, `telefone`, `CPF`) VALUES ('eric.sa2009@aluno.ifsc.edu.br', 'Eric da Silveira Arend', '12345', '47999999999', '00000000004');
INSERT INTO `ifsc60`.`usuario` (`email`, `nome`, `senha`, `telefone`, `CPF`) VALUES ('maria.s2009@aluno.ifsc.edu.br', 'Maria Eduarda dos Santos Schäfer', '12345', '47999999999', '00000000005');
INSERT INTO `ifsc60`.`usuario` (`email`, `nome`, `senha`, `telefone`, `CPF`) VALUES ('eli.ep2009@aluno.ifsc.edu.br', 'Eli Eric Freitas Pinheiro', '12345', '47999999999', '00000000006');
INSERT INTO `ifsc60`.`usuario` (`email`, `nome`, `senha`, `telefone`, `CPF`) VALUES ('fabiano.mjj27@aluno.ifsc.edu.br', 'Fabiano Marcelo Junkes Júnior', '12345', '47999999999', '00000000007');
INSERT INTO `ifsc60`.`usuario` (`email`, `nome`, `senha`, `telefone`, `CPF`) VALUES ('suelen.vicente@ifsc.edu.br', 'Suelen Vicente Vieira', '12345', '47999999999', '00000000008');
INSERT INTO `ifsc60`.`usuario` (`email`, `nome`, `senha`, `telefone`, `CPF`) VALUES ('joao.mtm@aluno.ifsc.edu.br', 'João Marcelo Thainer Meleu', '12345', '47999999999', '00000000009');

COMMIT;


-- -----------------------------------------------------
-- Data for table `ifsc60`.`bolsista`
-- -----------------------------------------------------
START TRANSACTION;
USE `ifsc60`;

INSERT INTO `ifsc60`.`bolsista` (`email`) VALUES ('kiara.s18@ifsc.edu.br');
INSERT INTO `ifsc60`.`bolsista` (`email`) VALUES ('heloisa.mr@aluno.ifsc.edu.br');
INSERT INTO `ifsc60`.`bolsista` (`email`) VALUES ('oliver.cs11@aluno.ifsc.edu.br');
INSERT INTO `ifsc60`.`bolsista` (`email`) VALUES ('eric.sa2009@aluno.ifsc.edu.br');
INSERT INTO `ifsc60`.`bolsista` (`email`) VALUES ('maria.s2009@aluno.ifsc.edu.br');
INSERT INTO `ifsc60`.`bolsista` (`email`) VALUES ('eli.ep2009@aluno.ifsc.edu.br');
INSERT INTO `ifsc60`.`bolsista` (`email`) VALUES ('fabiano.mjj27@aluno.ifsc.edu.br');



COMMIT;


-- -----------------------------------------------------
-- Data for table `ifsc60`.`coordenador`
-- -----------------------------------------------------
START TRANSACTION;
USE `ifsc60`;
INSERT INTO `ifsc60`.`coordenador` (`email`, `SIAPE`) VALUES ('suelen.vicente@ifsc.edu.br', '100001');



COMMIT;


-- -----------------------------------------------------
-- Data for table `ifsc60`.`ministrante`
-- -----------------------------------------------------
START TRANSACTION;
USE `ifsc60`;
INSERT INTO `ifsc60`.`ministrante` (`email`, `nome`, `telefone`) VALUES ('graciane@gmail.com', 'Graciane', '47955555555');
INSERT INTO `ifsc60`.`ministrante` (`email`, `nome`, `telefone`) VALUES ('pedro@gmail.com', 'Pedro', '47955555555');

COMMIT;

-- -----------------------------------------------------
-- Data for table `ifsc60`.`administrador`
-- -----------------------------------------------------
START TRANSACTION;

USE `ifsc60`;

INSERT INTO `administrador` (`email`) VALUES ('joao.mtm@aluno.ifsc.edu.br');

COMMIT;




-- -----------------------------------------------------
-- Data for table `ifsc60`.`oficina`
-- -----------------------------------------------------
START TRANSACTION;
USE `ifsc60`;
INSERT INTO `ifsc60`.`oficina` (`idOficina`, `ministrante_email`, `titulo`, `descricao`, `local`, `dt_inicio`, `dt_termino`, `duracaoHr`) VALUES (1, 'graciane@gmail.com', 'Curso MySQL', 'Curso...', 'IFSC Gaspar', '2026-09-08', '2026-09-09', 8);
INSERT INTO `ifsc60`.`oficina` (`idOficina`, `ministrante_email`, `titulo`, `descricao`, `local`, `dt_inicio`, `dt_termino`, `duracaoHr`) VALUES (2, 'pedro@gmail.com', 'Curso Javascript', 'Curso...', 'IFSC Gaspar', '2026-09-08', '2026-09-10', 8);

COMMIT;


-- -----------------------------------------------------
-- Data for table `ifsc60`.`dia`
-- -----------------------------------------------------
START TRANSACTION;
USE `ifsc60`;
INSERT INTO `ifsc60`.`dia` (`dtOficinaDia`) VALUES ('2026-09-08');
INSERT INTO `ifsc60`.`dia` (`dtOficinaDia`) VALUES ('2026-09-09');
INSERT INTO `ifsc60`.`dia` (`dtOficinaDia`) VALUES ('2026-09-10');

COMMIT;


-- -----------------------------------------------------
-- Data for table `ifsc60`.`participante`
-- -----------------------------------------------------
START TRANSACTION;
USE `ifsc60`;
INSERT INTO `ifsc60`.`participante` (`idParticipante`, `nome`, `CPF`, `telefone`) VALUES (1, 'Ana G. Gaulke ', NULL, NULL);
INSERT INTO `ifsc60`.`participante` (`idParticipante`, `nome`, `CPF`, `telefone`) VALUES (2, 'Beatriz ', NULL, NULL);
INSERT INTO `ifsc60`.`participante` (`idParticipante`, `nome`, `CPF`, `telefone`) VALUES (3, 'Elizangela Schmidt ', NULL, NULL);
INSERT INTO `ifsc60`.`participante` (`idParticipante`, `nome`, `CPF`, `telefone`) VALUES (4, 'Elza Guimarães Rickman', NULL, NULL);
INSERT INTO `ifsc60`.`participante` (`idParticipante`, `nome`, `CPF`, `telefone`) VALUES (5, 'Elza Satoko Kamigashima', NULL, NULL);
INSERT INTO `ifsc60`.`participante` (`idParticipante`, `nome`, `CPF`, `telefone`) VALUES (6, 'Luiza Schmidt ', NULL, NULL);
INSERT INTO `ifsc60`.`participante` (`idParticipante`, `nome`, `CPF`, `telefone`) VALUES (7, 'Magali Siqueira Correa ', NULL, NULL);
INSERT INTO `ifsc60`.`participante` (`idParticipante`, `nome`, `CPF`, `telefone`) VALUES (8, 'Maria Martha Losada  ', NULL, NULL);
COMMIT;


-- -----------------------------------------------------
-- Data for table `ifsc60`.`participa`
-- -----------------------------------------------------
START TRANSACTION;
USE `ifsc60`;
INSERT INTO `ifsc60`.`participa` (`idParticipante`, `dia_dtOficinaDia`, `oficina_idOficina`, `frequencia`) VALUES (1, '2026-09-08', 1, 0);
INSERT INTO `ifsc60`.`participa` (`idParticipante`, `dia_dtOficinaDia`, `oficina_idOficina`, `frequencia`) VALUES (1, '2026-09-09', 1, 1);
INSERT INTO `ifsc60`.`participa` (`idParticipante`, `dia_dtOficinaDia`, `oficina_idOficina`, `frequencia`) VALUES (2, '2026-09-08', 2, 1);
INSERT INTO `ifsc60`.`participa` (`idParticipante`, `dia_dtOficinaDia`, `oficina_idOficina`, `frequencia`) VALUES (2, '2026-09-10', 2, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `ifsc60`.`usuario_monitora_oficina`
-- -----------------------------------------------------
START TRANSACTION;
USE `ifsc60`;

INSERT INTO `ifsc60`.`usuario_monitora_oficina` (`usuario_email`, `oficina_idOficina`) VALUES ('kiara.s18@ifsc.edu.br', 1);
INSERT INTO `ifsc60`.`usuario_monitora_oficina` (`usuario_email`, `oficina_idOficina`) VALUES ('heloisa.mr@aluno.ifsc.edu.br', 1);
INSERT INTO `ifsc60`.`usuario_monitora_oficina` (`usuario_email`, `oficina_idOficina`) VALUES ('oliver.cs11@aluno.ifsc.edu.br', 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `ifsc60`.`oficina_acontece_dia`
-- -----------------------------------------------------
START TRANSACTION;
USE `ifsc60`;
INSERT INTO `ifsc60`.`oficina_acontece_dia` (`oficina_idOficina`, `dia_dtOficinaDia`) VALUES (1, '2026-09-08');
INSERT INTO `ifsc60`.`oficina_acontece_dia` (`oficina_idOficina`, `dia_dtOficinaDia`) VALUES (1, '2026-09-09');
INSERT INTO `ifsc60`.`oficina_acontece_dia` (`oficina_idOficina`, `dia_dtOficinaDia`) VALUES (2, '2026-09-08');
INSERT INTO `ifsc60`.`oficina_acontece_dia` (`oficina_idOficina`, `dia_dtOficinaDia`) VALUES (2, '2026-09-10');

COMMIT;


