-- MySQL Script generated by MySQL Workbench
-- Mon Sep 14 10:38:32 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

<<<<<<< HEAD:server/bancoDeDados.sql
CREATE USER IF NOT EXISTS 'oliver_11'@'localhost' IDENTIFIED BY 'oliver_11';
GRANT ALL PRIVILEGES ON ifsc60.* TO 'oliver_11'@'localhost';
FLUSH PRIVILEGES;
-- create tables
=======
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
>>>>>>> ac8251e7f641f0ed2445dde5951030c16f1dd022:bancoDeDados.sql

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ifsc60
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ifsc60` ;

-- -----------------------------------------------------
-- Schema ifsc60
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ifsc60` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `ifsc60` ;

<<<<<<< HEAD:server/bancoDeDados.sql
create table coordenador(
	email varchar(100) primary key not null,
	SIAPE varchar(20) not null,
    foreign key (email) references usuario (email) 
);

create table bolsista(
	email varchar(100) primary key not null,
    foreign key (email) references usuario (email) 
);

create table administrador(
	email varchar(100) primary key,
    foreign key (email) references usuario (email)
);

create table participante(
	idParticipante int auto_increment primary key not null,
    email varchar(100),
    foreign key (email) references administrador (email),
    nome varchar (200) not null,
    CPF varchar(11),
    telefone varchar (13)
    );
    
create table comparece (
	email varchar(100) primary key not null,
	foreign key (email) references bolsista (email),
    idOficina int auto_increment not null,
    foreign key (idOficina) references oficina (idOficina)
);

create table oficinaDia (
	idOficinaDia int auto_increment primary key not null,
    dt date not null
);

create table dia_oficina (
	idOficina int primary key not null,
	foreign key (idOficina) references oficina (idOficina),
	idOficinaDia int not null,
    foreign key (idOficinaDia) references oficinaDia (idOficinaDia)
);

create table participa (
	idParticipante int primary key not null, 
    idOficinaDia int not null,
    foreign key (idOficinaDia) references oficinaDia (idOficinaDia),
    foreign key (idParticipante) references participante (idParticipante),
    frequencia boolean
);

create table ministrante (
	email varchar(100) primary key not null, 
    nome varchar (200) not null,
    telefone varchar (13)
);

-- inserts

insert into usuario
values 
('suelen.vicente@ifsc.edu.br', 'Suelen Vicente Vieira', '12345', '44998682401', '00000000001'),
('fernanda.trentini@ifsc.edu.br', 'Fernanda Trentini', '12345', '47988888888', '00000000001'),
('oliver.cs11@aluno.ifsc.edu.br', 'Oliver Cristine Silva dos Santos', '12345', '47988171843', '00000000001'),
('heloisa.mr@aluno.ifsc.edu.br', 'Heloisa Mafra Reisch', '12345', '12345678900', '00000000001'),
('kiara.s18@aluno.ifsc.edu.br', 'Kiara Annelie de Souza Silva', '12345', '12345678900', '00000000001');

insert into coordenador 
values 
('suelen.vicente@ifsc.edu.br', '12345'),
('fernanda.trentini@ifsc.edu.br', '12345');

insert into bolsista 
values 
('heloisa.mr@aluno.ifsc.edu.br'),
('kiara.s18@aluno.ifsc.edu.br'),
('oliver.cs11@aluno.ifsc.edu.br');
=======
-- -----------------------------------------------------
-- Table `ifsc60`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ifsc60`.`usuario` (
  `email` VARCHAR(100) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(15) NULL DEFAULT NULL,
  `CPF` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ifsc60`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ifsc60`.`administrador` (
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`email`),
  CONSTRAINT `administrador_ibfk_1`
    FOREIGN KEY (`email`)
    REFERENCES `ifsc60`.`usuario` (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ifsc60`.`bolsista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ifsc60`.`bolsista` (
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`email`),
  CONSTRAINT `bolsista_ibfk_1`
    FOREIGN KEY (`email`)
    REFERENCES `ifsc60`.`usuario` (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ifsc60`.`coordenador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ifsc60`.`coordenador` (
  `email` VARCHAR(100) NOT NULL,
  `SIAPE` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`email`),
  CONSTRAINT `coordenador_ibfk_1`
    FOREIGN KEY (`email`)
    REFERENCES `ifsc60`.`usuario` (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ifsc60`.`ministrante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ifsc60`.`ministrante` (
  `email` VARCHAR(100) NOT NULL,
  `nome` VARCHAR(200) NOT NULL,
  `telefone` VARCHAR(15) NULL DEFAULT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ifsc60`.`oficina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ifsc60`.`oficina` (
  `idOficina` INT NOT NULL AUTO_INCREMENT,
  `ministrante_email` VARCHAR(100) NOT NULL,
  `titulo` VARCHAR(50) NOT NULL,
  `descricao` VARCHAR(1200) NULL DEFAULT NULL,
  `local` VARCHAR(1200) NULL DEFAULT NULL,
  `dt_inicio` DATE NOT NULL,
  `dt_termino` DATE NOT NULL,
  `duracaoHr` INT NOT NULL,
  PRIMARY KEY (`idOficina`),
  INDEX `fk_oficina_ministrante1_idx` (`ministrante_email` ASC) VISIBLE,
  CONSTRAINT `fk_oficina_ministrante1`
    FOREIGN KEY (`ministrante_email`)
    REFERENCES `ifsc60`.`ministrante` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ifsc60`.`dia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ifsc60`.`dia` (
  `dtOficinaDia` DATE NOT NULL,
  PRIMARY KEY (`dtOficinaDia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ifsc60`.`participante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ifsc60`.`participante` (
  `idParticipante` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `CPF` VARCHAR(14) NULL DEFAULT NULL,
  `telefone` VARCHAR(15) NULL DEFAULT NULL,
  PRIMARY KEY (`idParticipante`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ifsc60`.`participa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ifsc60`.`participa` (
  `idParticipante` INT NOT NULL,
  `dia_dtOficinaDia` DATE NOT NULL,
  `oficina_idOficina` INT NOT NULL,
  `frequencia` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`idParticipante`, `dia_dtOficinaDia`),
  INDEX `fk_participa_dia1_idx` (`dia_dtOficinaDia` ASC) VISIBLE,
  INDEX `fk_participa_oficina1_idx` (`oficina_idOficina` ASC) VISIBLE,
  CONSTRAINT `participa_ibfk_1`
    FOREIGN KEY (`idParticipante`)
    REFERENCES `ifsc60`.`participante` (`idParticipante`),
  CONSTRAINT `fk_participa_dia1`
    FOREIGN KEY (`dia_dtOficinaDia`)
    REFERENCES `ifsc60`.`dia` (`dtOficinaDia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_participa_oficina1`
    FOREIGN KEY (`oficina_idOficina`)
    REFERENCES `ifsc60`.`oficina` (`idOficina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ifsc60`.`recuperacao_senha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ifsc60`.`recuperacao_senha` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `codigo` VARCHAR(6) NOT NULL,
  `expira_em` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `email` (`email` ASC) VISIBLE,
  CONSTRAINT `recuperacao_senha_ibfk_1`
    FOREIGN KEY (`email`)
    REFERENCES `ifsc60`.`usuario` (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ifsc60`.`usuario_monitora_oficina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ifsc60`.`usuario_monitora_oficina` (
  `usuario_email` VARCHAR(100) NOT NULL,
  `oficina_idOficina` INT NOT NULL,
  PRIMARY KEY (`usuario_email`, `oficina_idOficina`),
  INDEX `fk_usuario_has_oficina_oficina1_idx` (`oficina_idOficina` ASC) VISIBLE,
  INDEX `fk_usuario_has_oficina_usuario1_idx` (`usuario_email` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_has_oficina_usuario1`
    FOREIGN KEY (`usuario_email`)
    REFERENCES `ifsc60`.`usuario` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_oficina_oficina1`
    FOREIGN KEY (`oficina_idOficina`)
    REFERENCES `ifsc60`.`oficina` (`idOficina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ifsc60`.`oficina_acontece_dia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ifsc60`.`oficina_acontece_dia` (
  `oficina_idOficina` INT NOT NULL,
  `dia_dtOficinaDia` DATE NOT NULL,
  PRIMARY KEY (`oficina_idOficina`, `dia_dtOficinaDia`),
  INDEX `fk_oficina_has_dia_dia1_idx` (`dia_dtOficinaDia` ASC) VISIBLE,
  INDEX `fk_oficina_has_dia_oficina1_idx` (`oficina_idOficina` ASC) VISIBLE,
  CONSTRAINT `fk_oficina_has_dia_oficina1`
    FOREIGN KEY (`oficina_idOficina`)
    REFERENCES `ifsc60`.`oficina` (`idOficina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_oficina_has_dia_dia1`
    FOREIGN KEY (`dia_dtOficinaDia`)
    REFERENCES `ifsc60`.`dia` (`dtOficinaDia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `ifsc60`.`usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `ifsc60`;
INSERT INTO `ifsc60`.`usuario` (`email`, `nome`, `senha`, `telefone`, `CPF`) VALUES ('ana.teste@ifsc.edu.br', 'Ana Teste', '12345', '47999999999', '00000000001');
INSERT INTO `ifsc60`.`usuario` (`email`, `nome`, `senha`, `telefone`, `CPF`) VALUES ('bruno.teste@ifsc.edu.br', 'Bruno Teste', '12345', '47999999999', '00000000002');
INSERT INTO `ifsc60`.`usuario` (`email`, `nome`, `senha`, `telefone`, `CPF`) VALUES ('carla.teste@aluno.ifsc.edu.br', 'Carla Teste', '12345', '47999999999', '00000000003');
INSERT INTO `ifsc60`.`usuario` (`email`, `nome`, `senha`, `telefone`, `CPF`) VALUES ('diego.teste@aluno.ifsc.edu.br', 'Diego Teste', '12345', '47999999999', '00000000004');
INSERT INTO `ifsc60`.`usuario` (`email`, `nome`, `senha`, `telefone`, `CPF`) VALUES ('elisa.teste@aluno.ifsc.edu.br', 'Elisa Teste', '12345', '47999999999', '00000000005');

COMMIT;


-- -----------------------------------------------------
-- Data for table `ifsc60`.`bolsista`
-- -----------------------------------------------------
START TRANSACTION;
USE `ifsc60`;
INSERT INTO `ifsc60`.`bolsista` (`email`) VALUES ('carla.teste@aluno.ifsc.edu.br');
INSERT INTO `ifsc60`.`bolsista` (`email`) VALUES ('diego.teste@aluno.ifsc.edu.br');
INSERT INTO `ifsc60`.`bolsista` (`email`) VALUES ('elisa.teste@aluno.ifsc.edu.br');

COMMIT;


-- -----------------------------------------------------
-- Data for table `ifsc60`.`coordenador`
-- -----------------------------------------------------
START TRANSACTION;
USE `ifsc60`;
INSERT INTO `ifsc60`.`coordenador` (`email`, `SIAPE`) VALUES ('ana.teste@ifsc.edu.br', '100001');
INSERT INTO `ifsc60`.`coordenador` (`email`, `SIAPE`) VALUES ('bruno.teste@ifsc.edu.br', '100002');

COMMIT;


-- -----------------------------------------------------
-- Data for table `ifsc60`.`ministrante`
-- -----------------------------------------------------
START TRANSACTION;
USE `ifsc60`;
INSERT INTO `ifsc60`.`ministrante` (`email`, `nome`, `telefone`) VALUES ('kiara@gmail.com', 'Kiara', '47955555555');
INSERT INTO `ifsc60`.`ministrante` (`email`, `nome`, `telefone`) VALUES ('pedro@gmail.com', 'Pedro', '47955555555');

COMMIT;


-- -----------------------------------------------------
-- Data for table `ifsc60`.`oficina`
-- -----------------------------------------------------
START TRANSACTION;
USE `ifsc60`;
INSERT INTO `ifsc60`.`oficina` (`idOficina`, `ministrante_email`, `titulo`, `descricao`, `local`, `dt_inicio`, `dt_termino`, `duracaoHr`) VALUES (1, 'kiara@gmail.com', 'Curso MySQL', 'Curso...', 'IFSC Gaspar', '2026-09-08', '2026-09-09', 8);
INSERT INTO `ifsc60`.`oficina` (`idOficina`, `ministrante_email`, `titulo`, `descricao`, `local`, `dt_inicio`, `dt_termino`, `duracaoHr`) VALUES (2, 'pedro@gmail.com', 'Curso Javascript', 'Curso...', 'IFSC Gaspar', '2026-09-08', '2026-09-10', 8);

COMMIT;


-- -----------------------------------------------------
-- Data for table `ifsc60`.`dia`
-- -----------------------------------------------------
START TRANSACTION;
USE `ifsc60`;
INSERT INTO `ifsc60`.`dia` (`dtOficinaDia`) VALUES ('2026-09-08');
INSERT INTO `ifsc60`.`dia` (`dtOficinaDia`) VALUES ('2026-09-09');
INSERT INTO `ifsc60`.`dia` (`dtOficinaDia`) VALUES ('2026-09-10');

COMMIT;


-- -----------------------------------------------------
-- Data for table `ifsc60`.`participante`
-- -----------------------------------------------------
START TRANSACTION;
USE `ifsc60`;
INSERT INTO `ifsc60`.`participante` (`idParticipante`, `nome`, `CPF`, `telefone`) VALUES (1, 'Sr. João', NULL, NULL);
INSERT INTO `ifsc60`.`participante` (`idParticipante`, `nome`, `CPF`, `telefone`) VALUES (2, 'Sra. Maria', NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `ifsc60`.`participa`
-- -----------------------------------------------------
START TRANSACTION;
USE `ifsc60`;
INSERT INTO `ifsc60`.`participa` (`idParticipante`, `dia_dtOficinaDia`, `oficina_idOficina`, `frequencia`) VALUES (1, '2026-09-08', 1, 0);
INSERT INTO `ifsc60`.`participa` (`idParticipante`, `dia_dtOficinaDia`, `oficina_idOficina`, `frequencia`) VALUES (1, '2026-09-09', 1, 1);
INSERT INTO `ifsc60`.`participa` (`idParticipante`, `dia_dtOficinaDia`, `oficina_idOficina`, `frequencia`) VALUES (2, '2026-09-08', 2, 1);
INSERT INTO `ifsc60`.`participa` (`idParticipante`, `dia_dtOficinaDia`, `oficina_idOficina`, `frequencia`) VALUES (2, '2026-09-10', 2, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `ifsc60`.`usuario_monitora_oficina`
-- -----------------------------------------------------
START TRANSACTION;
USE `ifsc60`;
INSERT INTO `ifsc60`.`usuario_monitora_oficina` (`usuario_email`, `oficina_idOficina`) VALUES ('carla.teste@aluno.ifsc.edu.br', 1);
INSERT INTO `ifsc60`.`usuario_monitora_oficina` (`usuario_email`, `oficina_idOficina`) VALUES ('diego.teste@aluno.ifsc.edu.br', 1);
INSERT INTO `ifsc60`.`usuario_monitora_oficina` (`usuario_email`, `oficina_idOficina`) VALUES ('elisa.teste@aluno.ifsc.edu.br', 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `ifsc60`.`oficina_acontece_dia`
-- -----------------------------------------------------
START TRANSACTION;
USE `ifsc60`;
INSERT INTO `ifsc60`.`oficina_acontece_dia` (`oficina_idOficina`, `dia_dtOficinaDia`) VALUES (1, '2026-09-08');
INSERT INTO `ifsc60`.`oficina_acontece_dia` (`oficina_idOficina`, `dia_dtOficinaDia`) VALUES (1, '2026-09-09');
INSERT INTO `ifsc60`.`oficina_acontece_dia` (`oficina_idOficina`, `dia_dtOficinaDia`) VALUES (2, '2026-09-08');
INSERT INTO `ifsc60`.`oficina_acontece_dia` (`oficina_idOficina`, `dia_dtOficinaDia`) VALUES (2, '2026-09-10');

COMMIT;

>>>>>>> ac8251e7f641f0ed2445dde5951030c16f1dd022:bancoDeDados.sql
